### ISSUE TITLE
Aurora related crash

### ISSUE THREAD

**Issue by tobi1449** [OreCruncher/BetterRain#6]
The players on our server are frequently experiencing this crash:

`java.lang.NullPointerException: Unexpected error   at org.blockartistry.mod.BetterRain.client.ClientEffectHandler.clientTick(ClientEffectHandler.java:235)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_854_ClientEffectHandler_clientTick_ClientTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2064)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)`

Seems to be caused by auroras in another dimension (you only check if there exists an aurora somewhere with auroras.size() > 0 and if it's in another dimension getNearestAurora returns null).

**Comment by OreCruncher** [comment]
Which version are you using?

**Comment by tobi1449** [comment]
0.1.10

**Comment by OreCruncher** [comment]
Posted version v1.0.1.1 that has the fix. http://minecraft.curseforge.com/projects/better-rain/files.  If you cannot pick up this update right away the players can turn off Auroras in their local configs to prevent the logic from processing.  Of course, they will have to remember to turn them back on once you update.

**Comment by tobi1449** [comment]
That was fast, thanks :)

**Comment by OreCruncher** [comment]
:)
