### ISSUE TITLE
[BUG] incompatibility with Tardis Mod

### ISSUE THREAD

**Issue by AlienXtream** [OreCruncher/BetterRain#75]
some how it stops any of the controls from working, which is weird cos this mod (yours) is client side....
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2420176-tardis-mod-updated-to-v0-994-on-25-12-2015

**Comment by OreCruncher** [comment]
Never used that mod before.  Which version of Dynamic Surroundings are you using?

**Comment by OreCruncher** [comment]
I'm seeing the following in the client log.  Appears there is an issue with darkcore.  Something related to network packet handling registration.  Using `darkcore-0.3-86.jar`.

```
[04:51:22] [Client thread/TRACE] [darkcore/darkcore]: Sending event FMLInitializationEvent to mod darkcore
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.InstantiationException
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.eventhandler.EventBus.register(EventBus.java:103)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.eventhandler.EventBus.register(EventBus.java:85)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.network.FMLEventChannel.register(FMLEventChannel.java:86)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at io.darkcraft.darkcore.mod.DarkcoreMod.init(DarkcoreMod.java:108)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at java.lang.reflect.Method.invoke(Method.java:497)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at java.lang.reflect.Method.invoke(Method.java:497)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at java.lang.reflect.Method.invoke(Method.java:497)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.client.Minecraft.startGame(Minecraft.java:597)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.client.Minecraft.run(Minecraft.java:942)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.client.main.Main.main(Main.java:164)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at java.lang.reflect.Method.invoke(Method.java:497)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
[04:51:22] [Client thread/INFO] [STDERR/darkcore]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at GradleStart.main(Unknown Source)
[04:51:22] [Client thread/TRACE] [darkcore/darkcore]: Sent event FMLInitializationEvent to mod darkcore
```

**Comment by OreCruncher** [comment]
DarkholmeTenk/TardisModIssues#441

**Comment by OreCruncher** [comment]
Workaround posted to DarkholmeTenk/TardisModIssues#434.

**Comment by OreCruncher** [comment]
Posted BETA with a fix: http://minecraft.curseforge.com/projects/dynamic-surroundings/files
