### ISSUE TITLE
Client crash. FTB unstable 3.0.28, mod: 2.0.3.2

### ISSUE THREAD

**Issue by jikuja** [OreCruncher/BetterRain#92]
Dynamic surroundings crashed game

crash report: https://paste.ee/p/X9j8Y Checked newest commit and did not find fixes for this.

tldr:

```
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
    at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
    at org.blockartistry.mod.DynSurround.client.AuroraEffectHandler.getClosestAurora(AuroraEffectHandler.java:83)
    at org.blockartistry.mod.DynSurround.client.AuroraEffectHandler.process(AuroraEffectHandler.java:120)
    at org.blockartistry.mod.DynSurround.client.ClientEffectHandler.clientTick(ClientEffectHandler.java:112)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_470_ClientEffectHandler_clientTick_ClientTickEvent.invoke(.dynamic)
```

**Comment by OreCruncher** [comment]
Posted *.0.5.0BETA to CurseForge with the fix.
